---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ihsgzapd/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R favicon $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scss $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp CONTRIBUTING.md $DEPLOYPATH
    - /bin/cp curriculum.html $DEPLOYPATH
    - /bin/cp events.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp recaps.html $DEPLOYPATH
    - /bin/cp semester1.html $DEPLOYPATH
    - /bin/cp semester2.html $DEPLOYPATH
    - /bin/cp prepos-6.config $DEPLOYPATH
